#
#  Music Module | SBDS
# Configuration | By TIMURishche
#

#
# Music Module використовує Lavalink для програвання музики.
# Ви можете завантажити й налаштувати його вручну, або ж просто дозволити нам самим усе зробити за вас.
# https://github.com/lavalink-devs/Lavalink
#

# Якщо ви бажаєте використовувати власний Lavalink сервер, увімкніть цей параметр.
manual-setup: false

# Цей параметр буде проігноровано, якщо manual-setup == false.
# Ноди lavalink. Можете вказати декілька для розподілення навантаження.
nodes:
  - name: "main"
    url: "https://survivalboom.net"
    password: "dinoZaveriiik!!"