/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "SurvivalBoom Discord Service"

include("api")
include("core")

// Шукаємо усі модулі в проєкт й підключаємо їх.
rootDir.walkTopDown()
    .maxDepth(3) // По желанию: ограничьте глубину поиска, чтобы сборка не тормозила
    .filter { it.isDirectory && file("${it.path}/build.gradle.kts").exists() }
    .forEach { dir ->
        // Получаем относительный путь от корня и превращаем его в Gradle-путь (например, :core:network)
        val relativePath = dir.relativeTo(rootDir).path.replace(File.separator, ":")
        if (relativePath.isNotEmpty()) {
            include(":$relativePath")
        }
    }
