#
#    ________  ____  ____   _______  ___      ___  __  ___      ___  __      ___       _______     ______      ______   ___      ___
#   /"       )("  _||_ " | /"      \|"  \    /"  ||" \|"  \    /"  |/""\    |"  |     |   _  "\   /    " \    /    " \ |"  \    /"  |
#  (:   \___/ |   (  ) : ||:        |\   \  //  / ||  |\   \  //  //    \   ||  |     (. |_)  :) // ____  \  // ____  \ \   \  //   |
#   \___  \   (:  |  | . )|_____/   ) \\  \/. ./  |:  | \\  \/. .//' /\  \  |:  |     |:     \/ /  /    ) :)/  /    ) :)/\\  \/.    |
#    __/  \\   \\ \__/ //  //      /   \.    //   |.  |  \.    ////  __'  \  \  |___  (|  _  \\(: (____/ //(: (____/ //|: \.        |
#   /" \   :)  /\\ __ //\ |:  __   \    \\   /    /\  |\  \\   //   /  \\  \( \_|:  \ |: |_)  :)\        /  \        / |.  \    /:  |
#  (_______/  (__________)|__|  \___)    \__/    (__\_|_)  \__/(___/    \___)\_______)(_______/  \"_____/    \"_____/  |___|\__/|___|
#
#                        SurvivalBoom Discord Service | By TIMURishche | SurvivalBoom Network 2025
#                                           Наш власний дискорд бот. Ми - найкращі!
#
#                                                     ! КОНФІГУРАЦІЯ !


#
# У цьому файлі знаходиться базова конфігурація ядра SBDS.
# Сам по собі SBDS нічого не робить, а тільки надає API для розробки модулів.
# Увесь функціонал SBDS реалізований за допомогою модулів - окремих .jar файлів із кодом.
#
# Налаштування кожного з модулів знаходиться у modules/назва-модуля/config.yml (якщо модуль взагалі має якісь налаштування)
# У більшості випадків, модулі зберігають конфігурацію персонально для кожного користувача або сервера у базі даних SBDS.
# Це зроблено для того, щоб SBDS можна було використовувати на різних серверах одночасно.
#

# База даних SBDS.
# Саме у базі даних зберігаються усі дані про користувачів,
# а також налаштування інших діскорд серверів якщо ви дозволите це.
# SBDS використовує PostgreSQL як базу даних.
database:

  host: survivalboom.net:5432 # Хост бази даних.
  database: mydb

  # Якщо вам потрібно налаштувати щось специфічне, можете налаштувати JDBC напряму.
  # (Параметр host та database ігнорується якщо параметр jdbc існує)
  # jdbc: "jdbc:postgresql://survivalboom.net:5432/mydb"

  user: dinoZavrik # Користувач.
  password: abobus2024 # Пароль.

  # SBDS використовує HikariCP для роботи із базою даних.
  # У цій секції ви можете налаштувати специфічні параметри Hikari.
  # Якщо ви не впевнені що ці налаштування означають, не чіпайте їх.
  # Ви можете видалити параметр або усю секцію взагалі, аби SBDS використовував значення за замовчуванням.
  hikari:

    pool-size: 10
    min-idle: 2
    idle-timeout: 30000
    lifetime: 1800000
    connection-timeout: 3000
    driver: "org.postgresql.Driver"


translations:

  # Переклад який буде використовуватись за замовчуванням
  # у випадку якщо користувач не встановив переклад для себе.
  default: english

  # Резервний переклад. Використовується у випадках коли повідомлення не знайдено у перекладі користувача.
  # Якщо повідомлення не буде знайдено навіть у цьому перекладі,
  # замість необхідного повідомлення буде просто плейсхолдер `$[path.to.message]`.
  fallback: ukrainian

  # Чи надсилати у консоль попередження про повідомлення яке було не знайдно у перекладі?
  # true - Кожен раз коли SBDS не знайде повідомлення з перекладу, у консоль буде надіслано попередження.
  # false - SBDS буде просто ігнорувати подібні ситуації.
  warn-missing: true